# Generated by Django 6.0.3 on 2026-03-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('published_year', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
    ]
