# Generated by Django 6.0.3 on 2026-03-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ishlab_chiqaruvchi', models.CharField(max_length=200)),
                ('ishlab_chiqarilgan_sana', models.DateField()),
                ('amal_muddati', models.DateField()),
                ('miqdor', models.IntegerField()),
                ('kategoriya', models.CharField(max_length=100)),
            ],
        ),
    ]
